/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dewangga, Hendro, Ave
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private final ZooApp app;
    private final CardLayout card;
    public App() {
        initComponents();
        app = new ImplementANN("zoo.model","zoo.normalize");
        card = (CardLayout)panelHasil.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_ = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        teksNama = new javax.swing.JTextField();
        panelKaki = new javax.swing.JPanel();
        tb16_0 = new javax.swing.JToggleButton();
        tb16_1 = new javax.swing.JToggleButton();
        tb16_2 = new javax.swing.JToggleButton();
        tb16_3 = new javax.swing.JToggleButton();
        labelNama = new javax.swing.JLabel();
        panelMorfologi = new javax.swing.JPanel();
        tb01 = new javax.swing.JToggleButton();
        tb02 = new javax.swing.JToggleButton();
        tb08 = new javax.swing.JToggleButton();
        tb12 = new javax.swing.JToggleButton();
        tb13 = new javax.swing.JToggleButton();
        tb09 = new javax.swing.JToggleButton();
        tb10 = new javax.swing.JToggleButton();
        tb15 = new javax.swing.JToggleButton();
        panelKemampuan = new javax.swing.JPanel();
        tb05 = new javax.swing.JToggleButton();
        tb11 = new javax.swing.JToggleButton();
        tb06 = new javax.swing.JToggleButton();
        panelPerilaku = new javax.swing.JPanel();
        tb03 = new javax.swing.JToggleButton();
        tb04 = new javax.swing.JToggleButton();
        tb07 = new javax.swing.JToggleButton();
        tb14 = new javax.swing.JToggleButton();
        tombolOK = new javax.swing.JButton();
        panelHasil = new javax.swing.JPanel();
        panel0 = new javax.swing.JPanel();
        label0 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        gambarMamalia = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        labelMamalia = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        gambarBurung = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        labelBurung = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        gambarReptil = new javax.swing.JLabel();
        nama3 = new javax.swing.JLabel();
        labelReptil1 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        gambarIkan = new javax.swing.JLabel();
        nama4 = new javax.swing.JLabel();
        labelIkan1 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        gambarAmfibi = new javax.swing.JLabel();
        nama5 = new javax.swing.JLabel();
        labelAmfibi1 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        gambarSerangga = new javax.swing.JLabel();
        nama6 = new javax.swing.JLabel();
        labelSerangga1 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        gambarInvertebrata = new javax.swing.JLabel();
        nama7 = new javax.swing.JLabel();
        labelInvertebrata1 = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klasifikasi Hewan");

        teksNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teksNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNamaFocusLost(evt);
            }
        });

        panelKaki.setBorder(javax.swing.BorderFactory.createTitledBorder("Punya Berapa Kaki ?"));

        tb_.add(tb16_0);
        tb16_0.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        tb16_0.setText("NO");
        tb16_0.setToolTipText("Tidak Berkaki?");
        tb16_0.setMaximumSize(new java.awt.Dimension(40, 30));
        tb16_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb16_0ActionPerformed(evt);
            }
        });

        tb_.add(tb16_1);
        tb16_1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        tb16_1.setText("2");
        tb16_1.setToolTipText("Memiliki Dua Kaki?");
        tb16_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb16_1ActionPerformed(evt);
            }
        });

        tb_.add(tb16_2);
        tb16_2.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        tb16_2.setText("4");
        tb16_2.setToolTipText("Memiliki Empat Kaki?");
        tb16_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb16_2ActionPerformed(evt);
            }
        });

        tb_.add(tb16_3);
        tb16_3.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        tb16_3.setText(">4");
        tb16_3.setToolTipText("Memiliki Banyak Kaki?");
        tb16_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb16_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKakiLayout = new javax.swing.GroupLayout(panelKaki);
        panelKaki.setLayout(panelKakiLayout);
        panelKakiLayout.setHorizontalGroup(
            panelKakiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKakiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb16_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb16_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb16_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb16_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKakiLayout.setVerticalGroup(
            panelKakiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKakiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKakiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb16_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb16_0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb16_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb16_3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        labelNama.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelNama.setLabelFor(labelNama);
        labelNama.setText("Nama Hewan");

        panelMorfologi.setBorder(javax.swing.BorderFactory.createTitledBorder("Morfologi"));

        tb01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/hair.png"))); // NOI18N
        tb01.setToolTipText("Memiliki Rambut?");
        tb01.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        tb01.setInheritsPopupMenu(true);
        tb01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb01ActionPerformed(evt);
            }
        });

        tb02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/feather.png"))); // NOI18N
        tb02.setToolTipText("Memiliki Bulu?");
        tb02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb02ActionPerformed(evt);
            }
        });

        tb08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/tooth.png"))); // NOI18N
        tb08.setToolTipText("Memiliki Gigi?");
        tb08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb08ActionPerformed(evt);
            }
        });

        tb12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/fins.png"))); // NOI18N
        tb12.setToolTipText("Bersirip?");
        tb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb12ActionPerformed(evt);
            }
        });

        tb13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/tail.png"))); // NOI18N
        tb13.setToolTipText("Berekor?");
        tb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb13ActionPerformed(evt);
            }
        });

        tb09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/backbone.png"))); // NOI18N
        tb09.setToolTipText("Memiliki Tulang Belakang?");
        tb09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb09ActionPerformed(evt);
            }
        });

        tb10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/breath.png"))); // NOI18N
        tb10.setToolTipText("Bernapas?");
        tb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb10ActionPerformed(evt);
            }
        });

        tb15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/cat_size.png"))); // NOI18N
        tb15.setToolTipText("Seukuran Kucing antau Anjing?");
        tb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMorfologiLayout = new javax.swing.GroupLayout(panelMorfologi);
        panelMorfologi.setLayout(panelMorfologiLayout);
        panelMorfologiLayout.setHorizontalGroup(
            panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMorfologiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb13)
                    .addComponent(tb01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb02, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb09, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb08, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb12)
                    .addComponent(tb15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMorfologiLayout.setVerticalGroup(
            panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMorfologiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb12)
                    .addComponent(tb08)
                    .addComponent(tb02)
                    .addComponent(tb01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMorfologiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb09)
                    .addComponent(tb10)
                    .addComponent(tb13)
                    .addComponent(tb15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb01.getAccessibleContext().setAccessibleName("tb01");
        tb10.getAccessibleContext().setAccessibleDescription("Bernapas Dengan Paru-paru?");

        panelKemampuan.setBorder(javax.swing.BorderFactory.createTitledBorder("Kemampuan"));

        tb05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/airborne.png"))); // NOI18N
        tb05.setToolTipText("Bisa terbang?");
        tb05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb05ActionPerformed(evt);
            }
        });

        tb11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/venomous.png"))); // NOI18N
        tb11.setToolTipText("Beracun?");
        tb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb11ActionPerformed(evt);
            }
        });

        tb06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/aquatic.png"))); // NOI18N
        tb06.setToolTipText("Hidup di Air?");
        tb06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb06ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKemampuanLayout = new javax.swing.GroupLayout(panelKemampuan);
        panelKemampuan.setLayout(panelKemampuanLayout);
        panelKemampuanLayout.setHorizontalGroup(
            panelKemampuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKemampuanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb05)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb06)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKemampuanLayout.setVerticalGroup(
            panelKemampuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKemampuanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKemampuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb06)
                    .addComponent(tb11)
                    .addComponent(tb05))
                .addContainerGap())
        );

        panelPerilaku.setBorder(javax.swing.BorderFactory.createTitledBorder("Perilaku"));

        tb03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/egg.png"))); // NOI18N
        tb03.setToolTipText("Bertelur?");
        tb03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb03ActionPerformed(evt);
            }
        });

        tb04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/milk.png"))); // NOI18N
        tb04.setToolTipText("Menyusui?");
        tb04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb04ActionPerformed(evt);
            }
        });

        tb07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/predator.png"))); // NOI18N
        tb07.setToolTipText("Pemangsa?");
        tb07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb07ActionPerformed(evt);
            }
        });

        tb14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/domestic.png"))); // NOI18N
        tb14.setToolTipText("Hewan yang Dipelihara?");
        tb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPerilakuLayout = new javax.swing.GroupLayout(panelPerilaku);
        panelPerilaku.setLayout(panelPerilakuLayout);
        panelPerilakuLayout.setHorizontalGroup(
            panelPerilakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerilakuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb07)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPerilakuLayout.setVerticalGroup(
            panelPerilakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerilakuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerilakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb14)
                    .addComponent(tb07)
                    .addComponent(tb04)
                    .addComponent(tb03))
                .addContainerGap())
        );

        tombolOK.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        tombolOK.setText("OK");
        tombolOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolOKActionPerformed(evt);
            }
        });

        panelHasil.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));
        panelHasil.setLayout(new java.awt.CardLayout());

        label0.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        label0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label0.setText("?");
        label0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel0Layout = new javax.swing.GroupLayout(panel0);
        panel0.setLayout(panel0Layout);
        panel0Layout.setHorizontalGroup(
            panel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label0, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        panel0Layout.setVerticalGroup(
            panel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label0, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        panelHasil.add(panel0, "panel0");

        gambarMamalia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/mamalia_1.jpg"))); // NOI18N

        nama1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama1.setText("nama");

        labelMamalia.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelMamalia.setText("Mamalia");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gambarMamalia)
                    .addComponent(nama1)
                    .addComponent(labelMamalia))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMamalia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarMamalia)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelHasil.add(panel1, "panel1");

        gambarBurung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/burung_2.jpg"))); // NOI18N

        nama2.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama2.setText("nama");

        labelBurung.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelBurung.setText("Burung");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gambarBurung)
                    .addComponent(nama2)
                    .addComponent(labelBurung))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBurung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarBurung)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelHasil.add(panel2, "panel2");

        gambarReptil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambarReptil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/reptil_3.jpg"))); // NOI18N

        nama3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama3.setText("nama");

        labelReptil1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelReptil1.setText("Reptil");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gambarReptil)
                    .addComponent(nama3)
                    .addComponent(labelReptil1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelReptil1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarReptil, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHasil.add(panel3, "panel3");

        gambarIkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ikan_4.jpg"))); // NOI18N

        nama4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama4.setText("nama");

        labelIkan1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelIkan1.setText("Ikan");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama4)
                    .addComponent(gambarIkan)
                    .addComponent(labelIkan1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIkan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarIkan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHasil.add(panel4, "panel4");

        gambarAmfibi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/amfibi_5.jpg"))); // NOI18N

        nama5.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama5.setText("nama");

        labelAmfibi1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelAmfibi1.setText("Amfibi");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama5)
                    .addComponent(gambarAmfibi)
                    .addComponent(labelAmfibi1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAmfibi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarAmfibi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHasil.add(panel5, "panel5");

        gambarSerangga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/serangga_6.jpg"))); // NOI18N

        nama6.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama6.setText("nama");

        labelSerangga1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelSerangga1.setText("Serangga");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama6)
                    .addComponent(gambarSerangga)
                    .addComponent(labelSerangga1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSerangga1)
                .addGap(2, 2, 2)
                .addComponent(gambarSerangga)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelHasil.add(panel6, "panel6");

        gambarInvertebrata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/invertebrata_7.jpg"))); // NOI18N

        nama7.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nama7.setText("nama");

        labelInvertebrata1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        labelInvertebrata1.setText("Invertebra");

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama7)
                    .addComponent(gambarInvertebrata)
                    .addComponent(labelInvertebrata1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInvertebrata1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarInvertebrata)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHasil.add(panel7, "panel7");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKaki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMorfologi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teksNama))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelKemampuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelPerilaku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(panelHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama)
                            .addComponent(teksNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelMorfologi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelPerilaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelKaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelKemampuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombolOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        panelKaki.getAccessibleContext().setAccessibleName("");

        labelJudul.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul.setText("KLASIFIKASI HEWAN");
        labelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Button Code"> 
    private void tb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb14ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb14ActionPerformed

    private void tb07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb07ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb07ActionPerformed

    private void tb04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb04ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb04ActionPerformed

    private void tb03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb03ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb03ActionPerformed

    private void tb06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb06ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb06ActionPerformed

    private void tb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb11ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb11ActionPerformed

    private void tb05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb05ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb05ActionPerformed

    private void tb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb15ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb15ActionPerformed

    private void tb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb10ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb10ActionPerformed

    private void tb09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb09ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb09ActionPerformed

    private void tb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb13ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb13ActionPerformed

    private void tb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb12ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb12ActionPerformed

    private void tb08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb08ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb08ActionPerformed

    private void tb02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb02ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb02ActionPerformed

    private void tb01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb01ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb01ActionPerformed

    private void tb16_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb16_3ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb16_3ActionPerformed

    private void tb16_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb16_2ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb16_2ActionPerformed

    private void tb16_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb16_1ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb16_1ActionPerformed

    private void tb16_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb16_0ActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_tb16_0ActionPerformed
    //* </editor-fold> */
    
    private void tombolOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolOKActionPerformed
        // TODO add your handling code here:
        String nama = teksNama.getText();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(mainPanel, 
                    "Nama Hewan masih kosong.\nIsi Nama Hewan terlebih dahulu!", 
                    "Nama Hewan Kosong", 
                    JOptionPane.WARNING_MESSAGE);
            
        } else {
            double input[] = 
                    {
                        toDouble(tb01.isSelected()),
                        toDouble(tb02.isSelected()),
                        toDouble(tb03.isSelected()),
                        toDouble(tb04.isSelected()),
                        toDouble(tb05.isSelected()),
                        toDouble(tb06.isSelected()),
                        toDouble(tb07.isSelected()),
                        toDouble(tb08.isSelected()),
                        toDouble(tb09.isSelected()),
                        toDouble(tb10.isSelected()),
                        toDouble(tb11.isSelected()),
                        toDouble(tb12.isSelected()),
                        toDouble(tb16_0.isSelected()),
                        toDouble(tb16_1.isSelected()),
                        toDouble(tb16_2.isSelected()),
                        toDouble(tb16_3.isSelected()),
                        toDouble(tb13.isSelected()),
                        toDouble(tb14.isSelected()),
                        toDouble(tb15.isSelected())
                    };
            //double [] input1 = {0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0}; // Invertebrata
            app.setInput(input);
            ClassType output = app.getOutput();

            
            for (int i = 1; i < 8; i++) {
                if (output.getCode() == i) {
                    card.show(panelHasil, "panel"+i);
                    System.out.println("panel"+i);
                    break;
                } else {
                    back();
                }
            }
        }
    }//GEN-LAST:event_tombolOKActionPerformed

    private void teksNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaFocusLost
        // TODO add your handling code here:
        String text = " tergolong";
        javax.swing.JLabel[] labels = {nama1, nama2, nama3, nama4, nama5, nama6, nama7};
        for (JLabel label : labels) {
            label.setText(teksNama.getText() + text);
        }
    }//GEN-LAST:event_teksNamaFocusLost

    private void back() {
        card.show(panelHasil, "panel0");
    }
    private double toDouble (boolean select) {
        if (select) {
            return 1.0;
        }
        return 0.0;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gambarAmfibi;
    private javax.swing.JLabel gambarBurung;
    private javax.swing.JLabel gambarIkan;
    private javax.swing.JLabel gambarInvertebrata;
    private javax.swing.JLabel gambarMamalia;
    private javax.swing.JLabel gambarReptil;
    private javax.swing.JLabel gambarSerangga;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel labelAmfibi1;
    private javax.swing.JLabel labelBurung;
    private javax.swing.JLabel labelIkan1;
    private javax.swing.JLabel labelInvertebrata1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelMamalia;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelReptil1;
    private javax.swing.JLabel labelSerangga1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JLabel nama4;
    private javax.swing.JLabel nama5;
    private javax.swing.JLabel nama6;
    private javax.swing.JLabel nama7;
    private javax.swing.JPanel panel0;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panelHasil;
    private javax.swing.JPanel panelKaki;
    private javax.swing.JPanel panelKemampuan;
    private javax.swing.JPanel panelMorfologi;
    private javax.swing.JPanel panelPerilaku;
    private javax.swing.JToggleButton tb01;
    private javax.swing.JToggleButton tb02;
    private javax.swing.JToggleButton tb03;
    private javax.swing.JToggleButton tb04;
    private javax.swing.JToggleButton tb05;
    private javax.swing.JToggleButton tb06;
    private javax.swing.JToggleButton tb07;
    private javax.swing.JToggleButton tb08;
    private javax.swing.JToggleButton tb09;
    private javax.swing.JToggleButton tb10;
    private javax.swing.JToggleButton tb11;
    private javax.swing.JToggleButton tb12;
    private javax.swing.JToggleButton tb13;
    private javax.swing.JToggleButton tb14;
    private javax.swing.JToggleButton tb15;
    private javax.swing.JToggleButton tb16_0;
    private javax.swing.JToggleButton tb16_1;
    private javax.swing.JToggleButton tb16_2;
    private javax.swing.JToggleButton tb16_3;
    private javax.swing.ButtonGroup tb_;
    private javax.swing.JTextField teksNama;
    private javax.swing.JButton tombolOK;
    // End of variables declaration//GEN-END:variables
}
